using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VirtualNewOverride
{
    // readonly ≈ semi-constant
    abstract class Person
    {
        // protected because need to use in derived classes
        protected string _1stname, _Surname, _email;
        protected int _DoB;     // could be DateTime type
        protected int _Age;     // could be TimeSpan type and then change it

        #region Notes: 
        // Timespan: difference between two time, generated by operations between DateTime

        // constructors can take in a old instance      --    Aliasing
        //      when equate new instance to old one, doesn't simply copy -- BOTH POINT to the data "block", 
        //      ONE updates, TWO refreshes data;

        // private setter can be only set in the CLASS
        // protected: only class & DERIVED class
        // readonly: only in CONSTRUCTOR


        // Structs & int, string are VALUE types        --      copy
        // keyword ref make it REF types        copy -> edit
        // Objects are REFERENCE types      --      edit
        // ICloneable -- return a copy
        //               via the .Clone method
        #endregion

        internal Person(string First, string Last, string email, DateTime DoB)
        {
            _1stname = First;
            _Surname = Last;
            _email = email;
            _DoB = DoB.Year;
            _Age = DateTime.Now.Year - _DoB;
        }

        internal Person(string first, string last, DateTime DoB)
        {
            _1stname = first;
            _Surname = last;
            _DoB = DoB.Year;
            _Age = DateTime.Now.Year - _DoB;
        }


        public abstract int DateofBirth();

        public abstract bool ThisisAnAge(int age);

        public abstract bool IsOverAge();               // Q: WHY HAVE TO BE PUBLIC?

        public abstract string ChineseZodiac();

        public abstract string GenerateScrnName();

    }

    internal enum 生肖  // means Chinese Zodiac
    {
        // 1900, 2020 is the year of rat, so just 0

        申, 酉, 戌, 亥, 子, 丑, 寅, 卯, 辰, 巳, 午, 未
    //  猴  鸡  狗  猪  鼠  牛  虎  兔  龙  蛇  马  羊
    //  monkey       | rat                snake   sheep
    }
}
